### ISSUE TITLE
File does not move. Beets moves music files fine. None-ing operation

### ISSUE THREAD

**Issue by RollingStar** [gtronset/beets-filetote#110]
I changed my beets folder from myfolder to myfolder2 in the same parent folder. this folder does not exist.

Beets did create the folder and move all its music files to it. filetote did not move the toted files.

I also tried moving to a subfolder within myfolder. And I created it before using beets. Beets could move the music but filetote did not move the toted files.

Some permission weirdness may be happening. I did the best I could by chmod +777 before and after the move, but it didn't seem to be enough.

I am using Docker and ARM, running as root within the container which can trigger a lot of edge cases. https://github.com/beetbox/beets/discussions/4910

```
filetote:
    extensions: .*
    # It can also print what got left:
    print_ignored: yes
```

I notice I can trigger a None-ing operation from the code 

``` Python
self._log.info(
            f"{operation}-ing artifact:"
            f" {os.path.basename(util.displayable_path(artifact_dest))}"
        )
```

Is None supposed to be reachable normally?

https://github.com/gtronset/beets-filetote/blob/b14cbb92b776f975f61adeaca6a1f17980eedf01/beetsplug/filetote.py#L111

This person also got none-ing:
https://github.com/gtronset/beets-filetote/issues/35

```

root@77ac896c76f0:/#chmod -R +777 /fast/d/music/beetslibrary/ ; beet -vv mv gecs ; chmod -R +777 /fast/d/music/beetslibrary/
user configuration: /config/config.yaml
data directory: /config
plugin paths:
inline: adding item field i_cust_catalog
inline: adding item field i_short_catalog
inline: adding item field i_main
inline: adding album field alb_main
inline: adding album field alb_main_suffix
Sending event: pluginload
library database: /fast/d/music/beetslibrary/beets_library.db
library directory: /fast/d/music/beetslibrary
Sending event: library_opened
Moving 0 items (10 already in place).
Sending event: cli_exit
root@77ac896c76f0:/#chmod -R +777 /fast/d/music/beetslibrary/ ; beet -vv mv gecs ; chmod -R +777 /fast/d/music/beetslibrary/
user configuration: /config/config.yaml
data directory: /config
plugin paths:
inline: adding item field i_cust_catalog
inline: adding item field i_short_catalog
inline: adding item field i_main
inline: adding album field alb_main
inline: adding album field alb_main_suffix
Sending event: pluginload
library database: /fast/d/music/beetslibrary/beets_library.db
library directory: /fast/d/music/beetslibrary/temp
Sending event: library_opened
Moving 10 items.
moving: /fast/d/music/beetslibrary/100 gecs [2019] - 1000 gecs/01. 745 sticky.mp3
Sending event: before_item_moved
Sending event: item_moved
could not get filesize: [Errno 2] No such file or directory: b'/fast/d/music/beetslibrary/100 gecs [2019] - 1000 gecs/01. 745 sticky.mp3'
Sending event: database_change
Sending event: database_change
moving: /fast/d/music/beetslibrary/100 gecs [2019] - 1000 gecs/02. money machine.mp3
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
moving: /fast/d/music/beetslibrary/100 gecs [2019] - 1000 gecs/03. 800db cloud.mp3
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
moving: /fast/d/music/beetslibrary/100 gecs [2019] - 1000 gecs/04. I Need Help Immediately.mp3
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
moving: /fast/d/music/beetslibrary/100 gecs [2019] - 1000 gecs/05. stupid horse.mp3
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
moving: /fast/d/music/beetslibrary/100 gecs [2019] - 1000 gecs/06. xXXi_wud_nvrstop_UXXx.mp3
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
moving: /fast/d/music/beetslibrary/100 gecs [2019] - 1000 gecs/07. ringtone.mp3
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
moving: /fast/d/music/beetslibrary/100 gecs [2019] - 1000 gecs/08. gecgecgec.mp3
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
moving: /fast/d/music/beetslibrary/100 gecs [2019] - 1000 gecs/09. hand crushed by a mallet.mp3
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
moving: /fast/d/music/beetslibrary/100 gecs [2019] - 1000 gecs/10. gec 2 U.mp3
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: cli_exit
filetote: None-ing artifact: 00-100_gecs-1000_gecs-(mds003)-web-2019.jpg
Traceback (most recent call last):
  File "/usr/bin/beet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/beets/ui/__init__.py", line 1782, in main
    _raw_main(args)
  File "/usr/lib/python3.11/site-packages/beets/ui/__init__.py", line 1771, in _raw_main
    plugins.send('cli_exit', lib=lib)
  File "/usr/lib/python3.11/site-packages/beets/plugins.py", line 488, in send
    result = handler(**arguments)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/beets/plugins.py", line 145, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/beetsplug/filetote.py", line 420, in process_events
    self.process_artifacts(
  File "/usr/lib/python3.11/site-packages/beetsplug/filetote.py", line 580, in process_artifacts
    self.manipulate_artifact(artifact_source, artifact_dest)
  File "/usr/lib/python3.11/site-packages/beetsplug/filetote.py", line 655, in manipulate_artifact
    raise AssertionError(f"unknown MoveOperation {operation}")
AssertionError: unknown MoveOperation None
```

**Comment by gtronset** [comment]
@RollingStar Thank you for reporting this. While very similar symptoms/outcome, this occurred due to Filetote not actually supporting the "move" CLI command, just `import`. This is now changed in `v0.4.5` and should work as expected for you!
