### ISSUE TITLE
Crash on import

### ISSUE THREAD

**Issue by arogl** [gtronset/beets-filetote#97]
```log
    https://www.deezer.com/album/<8-digits>
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates?
Traceback (most recent call last):
  File "C:\Python3\Lib\site-packages\musicbrainzngs\musicbrainz.py", line 497, in _safe_read
    f = opener.open(req)
        ^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Python3\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\Scripts\beet-script.py", line 33, in <module>
    sys.exit(load_entry_point('beets', 'console_scripts', 'beet')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\git\beets\beets\ui\__init__.py", line 1301, in main
    _raw_main(args)
  File "i:\git\beets\beets\ui\__init__.py", line 1288, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "i:\git\beets\beets\ui\commands.py", line 1034, in import_func
    import_files(lib, paths, query)
  File "i:\git\beets\beets\ui\commands.py", line 974, in import_files
    session.run()
  File "i:\git\beets\beets\importer.py", line 345, in run
    pl.run_parallel(QUEUE_SIZE)
  File "i:\git\beets\beets\util\pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "i:\git\beets\beets\util\pipeline.py", line 358, in run
    self.coro.send(msg)
  File "i:\git\beets\beets\util\pipeline.py", line 170, in coro
    task = func(*(args + (task,)))
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\git\beets\beets\importer.py", line 1626, in manipulate_files
    task.manipulate_files(
  File "i:\git\beets\beets\importer.py", line 771, in manipulate_files
    item.move(operation)
  File "i:\git\beets\beets\library.py", line 958, in move
    self.move_file(dest, operation)
  File "i:\git\beets\beets\library.py", line 854, in move_file
    plugins.send("item_moved", item=self, source=self.path,
  File "i:\git\beets\beets\plugins.py", line 488, in send
    result = handler(**arguments)
             ^^^^^^^^^^^^^^^^^^^^
  File "i:\git\beets\beets\plugins.py", line 145, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "I:\Git\beets-filetote\beetsplug\filetote.py", line 390, in collect_artifacts
    mapping=self._generate_mapping(item, destination),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\Git\beets-filetote\beetsplug\filetote.py", line 292, in _generate_mapping
    mapping_meta.update(beets_item.formatted())
  File "i:\git\beets\beets\library.py", line 453, in __getitem__
    value = self._get(key)
            ^^^^^^^^^^^^^^
  File "i:\git\beets\beets\library.py", line 441, in _get
    return self._get_formatted(self.model, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\git\beets\beets\dbcore\db.py", line 88, in _get_formatted
    value = model._type(key).format(model.get(key))
                                    ^^^^^^^^^^^^^^
  File "i:\git\beets\beets\library.py", line 690, in get
    return self._get(key, default, raise_=with_album)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\git\beets\beets\dbcore\db.py", line 373, in _get
    return getters[key](self)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\arogl\AppData\Roaming\beets\beetsplug\artistcountry.py", line 15, in memf
    cache[artist_id] = f(item)
                       ^^^^^^^
  File "C:\Users\arogl\AppData\Roaming\beets\beetsplug\artistcountry.py", line 24, in _tmpl_country
    artist_item = get_artist_by_id(item['mb_artistid'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\musicbrainzngs\musicbrainz.py", line 821, in get_artist_by_id
    return _do_mb_query("artist", id, includes, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\musicbrainzngs\musicbrainz.py", line 728, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\musicbrainzngs\musicbrainz.py", line 417, in __call__
    return self.fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\musicbrainzngs\musicbrainz.py", line 690, in _mb_request
    resp = _safe_read(opener, req, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\musicbrainzngs\musicbrainz.py", line 503, in _safe_read
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: HTTP Error 400: Bad Request
```

**Comment by gtronset** [comment]
Hi @arogl, can you please provide a copy of your Beet's config to help diagnose?

I suspect this is not Filetote's doing but the `400` from MusicBrains in the last line, being requested by the [artistcountry plugin](https://github.com/agrausem/beets-artistcountry). It looks like artistcountry depends on the `mb_artistid`, which might not be present if you're only using `deezer`?

Depending on your config, you could confirm this by simply removing `filetote` from the plugin list and use `$artist_country` in the media file's path (assuming it's not there already). Otherwise, as mentioned, please send your config and I can dig deeper.

**Comment by arogl** [comment]
@gtronset If I disable the `filetote` plugin then the problem disappears.

This may be to do with the new code you introduced for `0.4.1` to expose all fields, and updated for `0.4.2`. I'll try disabling `artistcountry` plugin but keeping `filetote` enabled.

I looked at my config and have no variable usage from `artistcountry`, so I'll try again

**Comment by gtronset** [comment]
@arogl Yeah, based on the stacktrace Beets is crashing based on a `400` and Filetote does not do any HTTP requests. If disabling the other plugin doesn't fix things please provide your config and I'll happily take a deeper look.

**Comment by arogl** [comment]
I have confirmed disabling the `artistcountry` plugin fixes the crash

Closing
